name: Execute Tests
on: [push]
jobs:
  CreateVenv:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Cache Virtual Environment
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
      - name: Create Virtual Environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv &&
          source .venv/bin/activate &&
          pip install -r requirements.txt
  CreateInputs:
    needs: [CreateVenv]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baskets:
          - 10
          - 100000
    steps:

      - name: Cache Input
        id: cache-input
        uses: actions/cache@v3
        with:
          path: example_${{ matrix.baskets }}.root
          key: input-example_${{ matrix.baskets }}.root-001
      - name: Check out repository code
        if: steps.cache-input.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Cache Virtual Environment
        if: steps.cache-input.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
      - name: Create Input File w/ ${{ matrix.baskets }} Baskets
        if: steps.cache-input.outputs.cache-hit != 'true'
        run: |
          source .venv/bin/activate &&
          python create_input.py example_${{ matrix.baskets }}.root 100000000 ${{ matrix.baskets }}
  RunTests:
    needs: [CreateVenv, CreateInputs]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thescript:
          - utest.py
          - ftest.py
          - ptest.py
        input:
          - example_10.root
          - example_100000.root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Virtual Environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
      - name: Cache Input
        uses: actions/cache@v3
        with:
          path: ${{ matrix.input }}
          key: input-${{ matrix.input }}-001
      - name: Run Scripts
        run: |
          source .venv/bin/activate &&
          python ${{ matrix.thescript }} ${{ matrix.input }}