name: Execute Tests
on: [push]
jobs:
  CreateVenv:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Cache Virtual Environment
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
      - name: Create Virtual Environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv &&
          source .venv/bin/activate &&
          pip install -r requirements.txt
  CreateInputs:
    runs-on: ubuntu-latest
    container: rootproject/root
    steps:
      - name: Cache Input
        id: cache-input
        uses: actions/cache@v3
        with:
          path: input.root
          key: input-input.root-001a
      - name: Check out repository code
        if: steps.cache-input.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Create Input File
        if: steps.cache-input.outputs.cache-hit != 'true'
        run: |
          root create_input.C && ls
  RunTests:
    needs: [CreateVenv, CreateInputs]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thescript:
          - utest.py
          - ftest.py
          - ptest.py
        input:
          - input.root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Virtual Environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
      - name: Cache Input
        uses: actions/cache@v3
        with:
          path: ${{ matrix.input }}
          key: input-${{ matrix.input }}-001a
      - name: Run Scripts
        run: |
          source .venv/bin/activate &&
          python ${{ matrix.thescript }} ${{ matrix.input }}