name: Execute Tests
on: [push]
jobs:
  CreateVenv:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Cache Virtual Environment
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
      - name: Create Virtual Environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv &&
          source .venv/bin/activate &&
          pip install -r requirements.txt
  DownloadInput:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Input
        id: cache-input
        uses: actions/cache@v2
        with:
          path: nano_dy.root
          key: input-001
      - name: Create Virtual Environment
        if: steps.cache-input.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root
  RunTests:
    needs: CreateVenv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thescript:
          - utest.py
          - ftest.py
          - ptest.py
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Virtual Environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
      - name: Cache Input
        uses: actions/cache@v2
        with:
          path: nano_dy.root
          key: input-001
      - name: Run Scripts
        run: |
          source .venv/bin/activate &&
          python ${{ matrix.thescript }}